[package]
name = "nekoup-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"

nekoup-config = { path = "../nekoup-config" }
nekoup-id = { path = "../nekoup-id" }